services:

  reader:
    container_name: reader
    image: agileworksnet/reader:latest
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./storage:/usr/src/app/storage
    ports:
      - "3000:3000"
