version: '3.9'

services:

  api:
    container_name: log-viewer
    image: log-viewer
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./storage:/usr/src/app/storage
    ports:
      - "3000:3000"
